// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-c8gGuiq4h1lFEVOnNm1_YbK21HKQoS0',
    appId: '1:973121984053:web:22acb70c2e4b881e9b437c',
    messagingSenderId: '973121984053',
    projectId: 'tech-trove-shop-3ea50',
    authDomain: 'tech-trove-shop-3ea50.firebaseapp.com',
    storageBucket: 'tech-trove-shop-3ea50.appspot.com',
    measurementId: 'G-9W9M8GWTVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWa2oMnwVYsUapCby5pyZNmzY3_z-denY',
    appId: '1:973121984053:android:eb57c772b96d8a919b437c',
    messagingSenderId: '973121984053',
    projectId: 'tech-trove-shop-3ea50',
    storageBucket: 'tech-trove-shop-3ea50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDclfP1BEp3JjUCBeVT-hMA4qDxcKRvZko',
    appId: '1:973121984053:ios:1a6df1c4187f26789b437c',
    messagingSenderId: '973121984053',
    projectId: 'tech-trove-shop-3ea50',
    storageBucket: 'tech-trove-shop-3ea50.appspot.com',
    iosBundleId: 'com.example.techTroveShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDclfP1BEp3JjUCBeVT-hMA4qDxcKRvZko',
    appId: '1:973121984053:ios:5e855787486492889b437c',
    messagingSenderId: '973121984053',
    projectId: 'tech-trove-shop-3ea50',
    storageBucket: 'tech-trove-shop-3ea50.appspot.com',
    iosBundleId: 'com.example.techTroveShop.RunnerTests',
  );
}
